name: hyper-controller

# required debian packages:
# xvfb, libsdl-image1.2-dev, libsdl-mixer1.2-dev, libsdl-ttf2.0-dev, libsdl1.2-dev, libportmidi-dev, libswscale-dev

# this limits the binary packages to either those that don't use binaries
# or those that use binaries compatible with the raspberry Pi
channels:
  - rpi
  - numba # for llvmlite

# you can add private repositories to the above channel list, just make sure that the target arch is correct

# Conda environment dependencies come in two forms:

# 1) conda dependencies (provide the best build tooling / integration). Mainly for binaries
# search the "rpi" conda package repository for binary/dll modules: `conda search -c rpi <PACKAGE>`

# all the packages are built by the berryconda repository (https://github.com/jjhelmus/berryconda/tree/master/recipes)
dependencies:
  - python=3.6.6
  - scipy=1.0.0
  - numpy=1.15.1
  - pyserial=3.4.0
  - cython=0.28.5
  - opencv=3.3.0
  - pandas=0.23.4
  - llvmlite=0.31.0dev0
  - jupyterlab=0.35.4
  - ipywidgets=7.4.1

  # 2) pypi packages (work for other python repositories). Mainly for python-code packages.
  # worse in terms of ease-of-integration because they often reference binaries on the path by name,
  # rather than including them as build arguments.
  - pip:
      - prompt_toolkit==1.0.15 # v2.0.4 currently has an incompatability with jupyter
      - picamera==1.13.0
      - pyngrok==1.4.0
      - sanic==19.9.0
      - Sanic-Cors==0.9.9.post1
      - scikit-kinematics==0.8.3
      - aiofile==1.5.2
      - ffmpy3==0.2.3 # needs a monkey patch to allow correct streaming
      - gpiozero==1.5.1
      - bqplot==0.12.1
      - librosa==0.7.1
      - matplotlib==3.1.1
      - sendgrid==6.1.0
      - jupyros==0.3.0
