name: hillary

channels:
  - defaults
  - conda-forge
  - numba

dependencies:
  - python=3.6.6
  - scipy=1.0.0
  - numpy=1.15.1
  - pyserial=3.4.0
  - cython=0.28.5
  - opencv=3.3.0
  - pandas=0.23.4
  - llvmlite=0.31.0dev0
  - ipywidgets=7.4.1
  - pip=20.0.2
  - nodejs==10.8.0

  # 2) pypi packages (work for other python repositories). Mainly for python-code packages.
  # worse in terms of ease-of-integration because they often reference binaries on the path by name,
  # rather than including them as build arguments.
  - pip:
      - jupyterlab==1.2.6
      - pyngrok==1.4.0
      - sanic==19.9.0
      - Sanic-Cors==0.9.9.post1
      - scikit-kinematics==0.8.3
      - aiofile==1.5.2
      - ffmpy3==0.2.3 # needs a monkey patch to allow correct streaming
      - gpiozero==1.5.1
      - bqplot==0.12.1
      - librosa==0.7.1
      - matplotlib==3.1.1
      - sendgrid==6.1.0
